name: CI Actions  # don't edit while the badge was depend on this

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*

  pull_request:
    branches:
      - main

jobs:
  lint-build-test:
    name: Lint/Test
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x, 1.18.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{matrix.go-version}}

      - name: Checkout Code Base
        uses: actions/checkout@v3

      - name: Restore Go Module Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      #      - name: Run golangci-lint
      #        uses: golangci/golangci-lint-action@v3.2.0

      - name: Build
        run: |
          go build -v ./...

      - name: Run Unit tests
        run: |
          go test -covermode=atomic -coverprofile=coverage.out ./...
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}